# Generated by Django 5.0.2 on 2024-03-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_customer_email_alter_product_digital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('dog', 'Dog Food'), ('cat', 'Cat Food')], default='default_category', max_length=255),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
